sudo: false
language: python

python:
  - '3.5'

os:
  - linux

virtualenv:
  system_site_packages: true

before_install:
  - pip install -r requirements-test.txt

install:
  - pip install -r requirements.txt

script:
  - python setup.py test

notifications:
  slack:
    secure: Az9G4l3zoYYTDLkEUJj/t0wqacM/ApCrr9RWWfP0PEinwBy7WlRxFUGrg3dhJ8rnfHBWmfndgQUvFqX7V3A9++85eqvj3Ik2y0bs/xcgundJRGpiEKKu2dvrfXP3uuvPrQI014Tbm3ZvA0aCTA1zz/iJTT8TUtm1pEAXRlbWUAzyfvqrNaMlfw0xFZ4nbIYwF8Fv+Q9TZ8cbAcgSOz9naMsYv/YOHSpviFOw6kMSNHoASP7vUrsxpCBqucJVXTlDdBz2IePUbbizZ5aEvRxQMKMCDFUb+j4K9prRvDJykCgYIkbGRwv3TNNjoingbtK2uC2awELUHwI+zg6Muyzc/xY1ngl3RPY7y71grLukzYSrY9T5onYtgU+4g42ioCebjlTbR5XsCqOLZS75cTqDPiU2lBca0nszAkQd+XzTz6nPPabnXY3ye9YNrutwsG6KFPppCFbuND8WzqmRIKH5yL7yviCW1jJrQIfk+ln3F6MyuFPt7Iqbse3U6tOsEr9usiGzrhbaRalc+QpJWZvF15DUgafbpVxAP31157Wxrz2bHPSJKbfPs4dGhY0VVd/IiCyhEe2IWWwQg04yLcLItZh80sthMkKu9WgLrPLlZ//0Zo5AgNduO50tyKKv+/Hk56bvcXSRFUK7jNxEnH4rKTGTBhjhJZ95N5uMlwOZDwE=
  email: false